module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#414750",
        "on-primary-fixed-variant": "#00497f",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        primary: "#004173",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#6fd2fb",
        "on-tertiary-container": "#7bd8ff",
        "inverse-primary": "#a0c9ff",
        "on-tertiary-fixed-variant": "#004d64",
        "inverse-surface": "#303030",
        "on-secondary-fixed-variant": "#7a3000",
        "tertiary-fixed": "#bde9ff",
        "secondary-container": "#fc7728",
        secondary: "#a04100",
        "on-primary-fixed": "#001c37",
        background: "#fbf9f8",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fbf9f8",
        "surface-container-high": "#eae8e7",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#001f2a",
        "secondary-fixed": "#ffdbcb",
        "surface-container-highest": "#e4e2e1",
        "primary-fixed": "#d2e4ff",
        "primary-container": "#00599a",
        tertiary: "#00455a",
        "on-surface": "#1b1c1c",
        "on-background": "#1b1c1c",
        "tertiary-container": "#005e79",
        "on-secondary-container": "#5d2300",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f3f0f0",
        "on-primary-container": "#acd0ff",
        "on-secondary-fixed": "#341000",
        "surface-variant": "#e4e2e1",
        "secondary-fixed-dim": "#ffb693",
        "surface-dim": "#dcd9d9",
        surface: "#fbf9f8",
        "outline-variant": "#c1c7d2",
        "surface-tint": "#1461a2",
        "surface-container-lowest": "#ffffff",
        outline: "#727781",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#a0c9ff",
      },
      fontFamily: {
        h1: ["Public Sans"],
        "label-caps": ["Inter"],
        "body-md": ["Inter"],
        h3: ["Public Sans"],
        "body-sm": ["Inter"],
        h2: ["Public Sans"],
        "data-num": ["Inter"],
        "body-lg": ["Inter"],
        display: ["Public Sans"],
      },
      fontSize: {
        h1: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        h3: ["16px", { lineHeight: "1.5", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "1.5", fontWeight: "400" }],
        h2: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "data-num": ["28px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        display: ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
